import type { CalendarAttendee, CalendarDayItem, CalendarEvent } from './calendarTypes';
import { addDays, toDateKey } from './calendarUtils';

const attendees = (...people: Array<[string, string, string]>): CalendarAttendee[] =>
  people.map(([id, name, color], index) => ({
    id,
    name,
    initials: name
      .split(' ')
      .map((part) => part[0])
      .join('')
      .slice(0, 2)
      .toUpperCase(),
    color: color || ['#1355ff', '#0f8b63', '#8c6df3', '#f59e0b', '#d92d20'][index % 5],
  }));

const team = attendees(
  ['a1', 'Alex Rivera', '#1355ff'],
  ['a2', 'Maya Chen', '#0f8b63'],
  ['a3', 'Jordan Lee', '#8c6df3'],
  ['a4', 'Sam Ortiz', '#f59e0b'],
  ['a5', 'Priya Shah', '#d92d20'],
  ['a6', 'Chris Park', '#425761'],
  ['a7', 'Nina Brooks', '#0c46e8'],
  ['a8', 'Leo Kim', '#b7791f'],
  ['a9', 'Ava Torres', '#8c6df3'],
  ['a10', 'Ben Walsh', '#0f8b63'],
  ['a11', 'Olivia Grant', '#1355ff'],
);

const dayOffset = (offset: number) => {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  return toDateKey(addDays(date, offset));
};

/** Seed events relative to today so the calendar always looks populated. */
export const createSeedEvents = (): CalendarEvent[] => [
  {
    id: 'seed-1',
    title: "Shah's Birthday",
    description: 'Cake and coffee in the lounge at noon.',
    category: 'birthday',
    date: dayOffset(-14),
    startMinutes: 12 * 60,
    endMinutes: 13 * 60,
  },
  {
    id: 'seed-2',
    title: 'Company Anniversary',
    description: 'Celebrate another year of Buddy.',
    category: 'anniversary',
    date: dayOffset(-12),
    startMinutes: 10 * 60,
    endMinutes: 11 * 60,
  },
  {
    id: 'seed-3',
    title: 'New Year Holiday',
    description: 'Office closed — enjoy the day off.',
    category: 'holiday',
    date: dayOffset(-10),
    startMinutes: 0,
    endMinutes: 23 * 60 + 59,
  },
  {
    id: 'seed-4',
    title: 'Weekly Team Sync',
    description: 'Standup, blockers, and sprint goals.',
    category: 'meeting',
    date: dayOffset(0),
    startMinutes: 11 * 60 + 20,
    endMinutes: 12 * 60 + 30,
    attendees: team,
    canJoin: true,
  },
  {
    id: 'seed-5',
    title: 'Holiday Break',
    description: 'Team half-day break.',
    category: 'holiday',
    date: dayOffset(0),
    startMinutes: 9 * 60,
    endMinutes: 10 * 60,
  },
  {
    id: 'seed-6',
    title: "Maya's Birthday Party",
    description: 'Bring a card if you can.',
    category: 'birthday',
    date: dayOffset(0),
    startMinutes: 9 * 60 + 30,
    endMinutes: 10 * 60 + 30,
  },
  {
    id: 'seed-7',
    title: 'Job Interview with Alex',
    description: 'Product designer final round.',
    category: 'interview',
    date: dayOffset(0),
    startMinutes: 14 * 60,
    endMinutes: 14 * 60 + 30,
    attendees: attendees(['a1', 'Alex Rivera', '#1355ff'], ['a2', 'Maya Chen', '#0f8b63']),
  },
  {
    id: 'seed-8',
    title: 'Product Anniversary',
    description: 'One year since v1 launch.',
    category: 'anniversary',
    date: dayOffset(2),
    startMinutes: 15 * 60,
    endMinutes: 16 * 60,
  },
  {
    id: 'seed-9',
    title: 'New Launch',
    description: 'Ship calendar integrations.',
    category: 'launch',
    date: dayOffset(4),
    startMinutes: 10 * 60,
    endMinutes: 11 * 60 + 30,
  },
  {
    id: 'seed-10',
    title: 'Onboarding Session',
    description: 'Welcome new hires to Buddy.',
    category: 'onboarding',
    date: dayOffset(6),
    startMinutes: 13 * 60,
    endMinutes: 14 * 60 + 30,
    attendees: attendees(
      ['a2', 'Maya Chen', '#0f8b63'],
      ['a3', 'Jordan Lee', '#8c6df3'],
      ['a4', 'Sam Ortiz', '#f59e0b'],
      ['a5', 'Priya Shah', '#d92d20'],
      ['a6', 'Chris Park', '#425761'],
    ),
  },
  {
    id: 'seed-11',
    title: 'Weekly Team Sync',
    description: 'Standup, blockers, and sprint goals.',
    category: 'meeting',
    date: dayOffset(7),
    startMinutes: 11 * 60 + 20,
    endMinutes: 12 * 60 + 30,
    attendees: team,
    canJoin: true,
  },
  {
    id: 'seed-12',
    title: "Jordan's Birthday",
    description: 'Virtual celebration after standup.',
    category: 'birthday',
    date: dayOffset(9),
    startMinutes: 16 * 60,
    endMinutes: 16 * 60 + 45,
  },
  {
    id: 'seed-13',
    title: 'Design Anniversary',
    description: 'Brand refresh milestone.',
    category: 'anniversary',
    date: dayOffset(12),
    startMinutes: 11 * 60,
    endMinutes: 12 * 60,
  },
  {
    id: 'seed-14',
    title: 'Job Interview',
    description: 'Engineering manager screen.',
    category: 'interview',
    date: dayOffset(14),
    startMinutes: 15 * 60,
    endMinutes: 15 * 60 + 45,
    attendees: attendees(['a1', 'Alex Rivera', '#1355ff'], ['a7', 'Nina Brooks', '#0c46e8']),
  },
  {
    id: 'seed-15',
    title: 'New Launch',
    description: 'Mobile companion soft launch.',
    category: 'launch',
    date: dayOffset(16),
    startMinutes: 9 * 60 + 30,
    endMinutes: 10 * 60 + 30,
  },
  {
    id: 'seed-16',
    title: 'Team Offsite Holiday',
    description: 'Optional remote day.',
    category: 'holiday',
    date: dayOffset(-3),
    startMinutes: 0,
    endMinutes: 23 * 60 + 59,
  },
  {
    id: 'seed-17',
    title: 'Client Review Call',
    description: 'Walk through Q3 roadmap updates.',
    category: 'meeting',
    date: dayOffset(1),
    startMinutes: 10 * 60,
    endMinutes: 11 * 60,
    attendees: attendees(['a1', 'Alex Rivera', '#1355ff'], ['a4', 'Sam Ortiz', '#f59e0b']),
    canJoin: true,
  },
  {
    id: 'seed-18',
    title: 'Design Critique',
    description: 'Calendar density and day summary review.',
    category: 'meeting',
    date: dayOffset(2),
    startMinutes: 11 * 60,
    endMinutes: 11 * 60 + 45,
    canJoin: true,
  },
];

/** Seed tasks, notes, and reminders linked to calendar dates. */
export const createSeedDayItems = (): CalendarDayItem[] => [
  {
    id: 'task-1',
    kind: 'task',
    title: 'Finalize Home empty states',
    description: 'Polish copy and primary actions for empty spaces.',
    date: dayOffset(0),
    timeMinutes: 9 * 60,
    priority: 'High',
  },
  {
    id: 'task-2',
    kind: 'task',
    title: 'Review calendar badges',
    description: 'Confirm meeting, task, note, and reminder counts read clearly.',
    date: dayOffset(0),
    timeMinutes: 13 * 60,
    priority: 'Medium',
  },
  {
    id: 'task-3',
    kind: 'task',
    title: 'Ship recording bar polish',
    description: 'Check collapsed sidebar inset and mobile padding.',
    date: dayOffset(0),
    done: true,
    priority: 'Low',
  },
  {
    id: 'note-1',
    kind: 'note',
    title: 'Standup talking points',
    description: 'Coverage for sync: blockers, demos, and follow-ups.',
    date: dayOffset(0),
    timeMinutes: 10 * 60 + 45,
  },
  {
    id: 'note-2',
    kind: 'note',
    title: 'Interview feedback draft',
    description: 'Capture strengths and next-step questions after Alex round.',
    date: dayOffset(0),
  },
  {
    id: 'reminder-1',
    kind: 'reminder',
    title: 'Send agenda before sync',
    description: 'Share the agenda 15 minutes before Weekly Team Sync.',
    date: dayOffset(0),
    timeMinutes: 11 * 60,
  },
  {
    id: 'reminder-2',
    kind: 'reminder',
    title: 'Prep join link',
    description: 'Confirm meeting link works on desktop and mobile.',
    date: dayOffset(0),
    timeMinutes: 11 * 60 + 10,
  },
  {
    id: 'task-4',
    kind: 'task',
    title: 'Write client recap',
    description: 'Summarize decisions from tomorrow’s review call.',
    date: dayOffset(1),
    priority: 'High',
  },
  {
    id: 'note-3',
    kind: 'note',
    title: 'Client questions',
    description: 'Pricing, timeline, and integration scope notes.',
    date: dayOffset(1),
  },
  {
    id: 'reminder-3',
    kind: 'reminder',
    title: 'Upload deck',
    description: 'Attach the latest roadmap slides before the call.',
    date: dayOffset(1),
    timeMinutes: 9 * 60 + 30,
  },
  {
    id: 'task-5',
    kind: 'task',
    title: 'Tighten week view density',
    description: 'Reduce padding when the right panel is open.',
    date: dayOffset(2),
    priority: 'Medium',
  },
  {
    id: 'task-6',
    kind: 'task',
    title: 'QA anniversary cards',
    description: 'Check anniversary chip colors in light theme.',
    date: dayOffset(2),
    priority: 'Low',
  },
  {
    id: 'note-4',
    kind: 'note',
    title: 'Critique checklist',
    description: 'Hierarchy, contrast, and overflow behavior.',
    date: dayOffset(2),
  },
  {
    id: 'reminder-4',
    kind: 'reminder',
    title: 'Book focus block',
    description: 'Protect 90 minutes after critique for fixes.',
    date: dayOffset(2),
    timeMinutes: 16 * 60,
  },
  {
    id: 'task-7',
    kind: 'task',
    title: 'Prep launch checklist',
    description: 'Marketing, support, and release notes owners.',
    date: dayOffset(4),
    priority: 'High',
  },
  {
    id: 'note-5',
    kind: 'note',
    title: 'Launch messaging',
    description: 'Short copy options for the in-app banner.',
    date: dayOffset(4),
  },
  {
    id: 'note-6',
    kind: 'note',
    title: 'Support macros',
    description: 'Draft macros for common launch questions.',
    date: dayOffset(4),
  },
  {
    id: 'reminder-5',
    kind: 'reminder',
    title: 'Freeze feature branch',
    description: 'No new calendar UI commits after 5pm.',
    date: dayOffset(4),
    timeMinutes: 17 * 60,
  },
  {
    id: 'task-8',
    kind: 'task',
    title: 'Onboarding workspace setup',
    description: 'Create starter spaces for new hires.',
    date: dayOffset(6),
    priority: 'Medium',
  },
  {
    id: 'reminder-6',
    kind: 'reminder',
    title: 'Send welcome pack',
    description: 'Email docs and calendar invites before session.',
    date: dayOffset(6),
    timeMinutes: 12 * 60,
  },
  {
    id: 'task-9',
    kind: 'task',
    title: 'Sync action items',
    description: 'Convert standup notes into tracked tasks.',
    date: dayOffset(7),
    priority: 'Medium',
  },
  {
    id: 'note-7',
    kind: 'note',
    title: 'Weekly highlights',
    description: 'Wins, risks, and decisions for leadership.',
    date: dayOffset(7),
  },
  {
    id: 'reminder-7',
    kind: 'reminder',
    title: 'Update capacity board',
    description: 'Refresh remaining monthly recording minutes.',
    date: dayOffset(7),
    timeMinutes: 10 * 60 + 30,
  },
];
